pub mod encoder;
pub mod binary_arithmetic;
pub mod basic_encoder;
pub mod logarithmic_encoder;
mod arithmetic_tests;
pub mod basic_with_fill_up;
pub mod fill_up_lite;
pub mod furlite_with_precedence;
mod performance_tests;
pub mod basic_with_precedence;